spring:
  application:
    name: boot-redis
  redis:
    client-name: wxw
    host: 127.0.0.1         #主机地址
    port: 6379              #端口号
    database: 1             #Redis数据库索引（默认为0）
    password:               #Redis服务器连接密码（默认为空）
    timeout: 1000ms         # 连接超时时间 默认100ms
    jedis:                  # lettuce redis 连接池
      pool:
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 0         # 连接池中的最小空闲连接


server:
  port: 7001